### ISSUE TITLE
Provided example doesn't work

### ISSUE THREAD

**Issue by kehwar** [jacob-j/vscode-folder-path-color#4] opened 2023-06-20 22:04 UTC
I can't make it work with the provided example

![image](https://github.com/jacob-j/vscode-folder-path-color/assets/45218102/62b2d06e-60ff-4618-b2df-c332b101f32c)

---

Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by colindrobinson** [comment] 2023-06-21 09:24
Ditto,  steps followed no colour change

**Comment by jacob-j** [comment] 2023-06-22 06:45
That is strange, I just created a new project with the extension installed, added your exact config and it works.
Maybe its a windows thing, I am on Mac. I'll try it on my PC and see if I can reproduce
@colindrobinson Are you also on Windows?

**Comment by jacob-j** [comment] 2023-06-22 07:01
Can confirm that the issue is Windows related, I have deployed a fix for this on version 0.0.12.
It now works on my Windows machine! :)

Was related to paths being a bit different on Windows

**Comment by colindrobinson** [comment] 2023-06-22 23:34
Fixed, good job Jacob.

**Closed** 2023-06-23 06:05 UTC
